name: detectorfreesfm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - torchvision=0.18.1
  - cudatoolkit=12.1
  - tqdm
  - matplotlib
  - pylint
  - conda-forge::h5py=3.1.0
  - conda-forge::loguru=0.5.3
  - conda-forge::scipy
  - conda-forge::ipdb
  - pip
  - pip:
    - -r requirements.txt
